[package]
name = "scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-sdk-sqs = "1.65.0"
lambda_runtime = "0.13.0"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["full"] }
