version = 0.1
[default.deploy.parameters]
stack_name = "tmdb-scraper"
resolve_s3 = true
s3_prefix = "tmdb-scraper"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
